-- DP Sistemas · esquema demo
-- Pegar en: Supabase → SQL Editor → Run
-- No apunta al proyecto de Ranas.

create table if not exists public.sedes (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  image text,
  status text default 'Activa',
  mp_access_token text,
  mp_public_key text,
  created_at timestamptz default now()
);

create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  role text not null default 'superadmin',
  sede_id bigint references public.sedes(id) on delete set null,
  created_at timestamptz default now()
);

create table if not exists public.students (
  id text primary key,
  name text not null,
  email text,
  password text,
  phone text,
  belt text default 'WHITE',
  classesattended integer default 0,
  classestonextbelt integer default 40,
  lastpaymentmonth text,
  lastpaymentdate text,
  ispaid boolean default false,
  plan text,
  monthlyfee integer,
  avatar text,
  birthdate text,
  history jsonb default '[]'::jsonb,
  scheduledclasses jsonb default '[]'::jsonb,
  joindate text,
  lastgrade text,
  graduationdate text,
  sede_id bigint references public.sedes(id) on delete set null,
    terms_accepted boolean default false,
  weight numeric,
  gender text,
  ficha jsonb default '{}'::jsonb
);

alter table public.students add column if not exists ficha jsonb default '{}'::jsonb;
alter table public.students add column if not exists progress jsonb default '{}'::jsonb;

create table if not exists public.videos (
  id text primary key,
  title text not null,
  description text,
  url text not null,
  thumbnail text,
  beltlevel text,
  category text,
  sede_id bigint references public.sedes(id) on delete set null
);

create table if not exists public.news (
  id integer primary key,
  title text not null,
  body text,
  img text,
  link text,
  label text,
  date text,
  stats jsonb default '[]'::jsonb,
  sede_id bigint references public.sedes(id) on delete set null
);

create sequence if not exists news_id_seq;
alter table public.news alter column id set default nextval('news_id_seq');

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  img text not null,
  size text default 'small',
  sede_id bigint references public.sedes(id) on delete set null
);

-- El backend usa la anon key sin Auth de Supabase (igual que el origen).
-- En un cliente real conviene service_role + RLS. Para la demo, acceso abierto.
alter table public.sedes enable row level security;
alter table public.admins enable row level security;
alter table public.students enable row level security;
alter table public.videos enable row level security;
alter table public.news enable row level security;
alter table public.gallery enable row level security;

drop policy if exists sedes_all on public.sedes;
drop policy if exists admins_all on public.admins;
drop policy if exists students_all on public.students;
drop policy if exists videos_all on public.videos;
drop policy if exists news_all on public.news;
drop policy if exists gallery_all on public.gallery;

create policy sedes_all on public.sedes for all using (true) with check (true);
create policy admins_all on public.admins for all using (true) with check (true);
create policy students_all on public.students for all using (true) with check (true);
create policy videos_all on public.videos for all using (true) with check (true);
create policy news_all on public.news for all using (true) with check (true);
create policy gallery_all on public.gallery for all using (true) with check (true);

grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
alter default privileges in schema public grant all on tables to anon, authenticated;
alter default privileges in schema public grant usage, select on sequences to anon, authenticated;

create table if not exists public.class_slots (
  id text primary key,
  name text not null,
  day text not null,
  start_time text not null,
  end_time text not null,
  teacher text default '',
  sede_id bigint references public.sedes(id) on delete set null,
  audience text default 'ADULTS',
  sort_order integer default 0,
  capacity integer
);

alter table public.class_slots add column if not exists capacity integer;

alter table public.class_slots enable row level security;
drop policy if exists class_slots_all on public.class_slots;
create policy class_slots_all on public.class_slots for all using (true) with check (true);
grant all on public.class_slots to anon, authenticated;

create table if not exists public.attendance (
  id text primary key,
  student_id text not null references public.students(id) on delete cascade,
  slot_id text,
  class_date date not null,
  checked_at timestamptz default now(),
  within_window boolean default true
);

create unique index if not exists attendance_unique_checkin
  on public.attendance (student_id, slot_id, class_date);

alter table public.attendance enable row level security;
drop policy if exists attendance_all on public.attendance;
create policy attendance_all on public.attendance for all using (true) with check (true);
grant all on public.attendance to anon, authenticated;

alter table public.videos add column if not exists format text default 'video';
alter table public.videos add column if not exists discipline text default 'Jiu Jitsu';
alter table public.videos add column if not exists belts jsonb default '[]'::jsonb;
alter table public.videos add column if not exists authorized_only boolean default false;
alter table public.videos add column if not exists duration text default '';

create table if not exists public.material_progress (
  id text primary key,
  student_id text not null,
  video_id text not null references public.videos(id) on delete cascade,
  progress integer default 0,
  views integer default 0,
  saved boolean default false,
  updated_at timestamptz default now()
);

create unique index if not exists material_progress_unique
  on public.material_progress (student_id, video_id);

alter table public.material_progress enable row level security;
drop policy if exists material_progress_all on public.material_progress;
create policy material_progress_all on public.material_progress for all using (true) with check (true);
grant all on public.material_progress to anon, authenticated;

create table if not exists public.events (
  id text primary key,
  slug text not null unique,
  title text not null,
  description text default '',
  photo text default '',
  rules_url text default '',
  rules_name text default '',
  event_date text,
  start_time text default '',
  end_time text default '',
  address text default '',
  capacity integer,
  paid boolean default true,
  price integer default 0,
  status text default 'draft',
  categories jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.event_registrations (
  id text primary key,
  event_id text not null references public.events(id) on delete cascade,
  kind text not null default 'guest',
  student_id text,
  name text not null,
  email text,
  phone text,
  document_id text,
  birth_date text,
  age integer,
  weight numeric,
  gender text,
  belt text,
  academy text,
  category_id text,
  category_name text,
  amount integer default 0,
  status text default 'pending',
  method text,
  created_at timestamptz default now()
);

create unique index if not exists event_reg_student_unique
  on public.event_registrations (event_id, student_id)
  where student_id is not null;

alter table public.events enable row level security;
alter table public.event_registrations enable row level security;
drop policy if exists events_all on public.events;
drop policy if exists event_registrations_all on public.event_registrations;
create policy events_all on public.events for all using (true) with check (true);
create policy event_registrations_all on public.event_registrations for all using (true) with check (true);
grant all on public.events to anon, authenticated;
grant all on public.event_registrations to anon, authenticated;

